version: '2'

services:
  web:
    image: nginx:1.12-alpine
    ports:
      - 80:80
    depends_on:
      - app
    volumes_from:
      - app

  app:
    image: dotnet-example
    volumes:
      - /app
      - /etc/nginx/conf.d/